export default {
    mapDispatchtoProps:(dispatch)=>{
        return {
            SetIsLogin:(status)=>{
                dispatch({
                    type:"SET_isLogin",
                    payload:status
                })
            },
            SetUser:(user)=>{
                dispatch({
                    type:"SET_User",
                    payload:user
                })
            },
            SetSelected:(selected)=>{
                dispatch({
                    type:"SET_Navigation",
                    payload:selected
                })
            },
            SetCheerPoint:(point)=>{
                dispatch({
                    type:"SET_CheerPoint",
                    payload:point
                })
            },
            dispatch:dispatch
        }
    },
    mapStatetoProps:(state)=>{
        return{
            store:state
        }
    }
}
